name: Release

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  create-release:
    name: Create GitHub release
    # only publish from the origin repository
    if: github.repository_owner == 'tokio-rs'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: "CHANGELOG.md"
          title: "$version"
          branch: v0.1.x
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
